insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Barcelona', 'Camp Nou', 'History of Barcelona', 2, 1, 0, 1, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Real Madrid', 'Santiago Bernabeu', 'History of Real Madrid', 1, 1, 1, 1, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Manchester United', 'Old Trafford', 'History of Manchester United', 1, 0, 1, 2, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Bayern Munich', 'Allianz Arena', 'History of Bayern Munich', 1, 2, 1, 0, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Juventus', 'Allianz Stadium', 'History of Juventus', 0, 1, 2, 1, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Liverpool', 'Anfield', 'History of Liverpool', 1, 1, 1, 1, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Paris Saint-Germain', 'Parc des Princes', 'History of Paris Saint-Germain', 0, 1, 2, 1, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Chelsea', 'Stamford Bridge', 'History of Chelsea', 2, 2, 0, 0, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Arsenal', 'Emirates Stadium', 'History of Arsenal', 2, 1, 0, 1, 0, 0);
insert into Teams (teams_name, home_field_name, history_description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('AC Milan', 'San Siro', 'History of AC Milan', 0, 0, 2, 2, 0, 0);

insert into Players (players_name, players_surname, team_id, position) values ('Lionel', 'Messi', 1, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Marc-André', 'ter Stegen', 1, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Gerard', 'Piqué', 1, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Jordi', 'Alba', 1, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Sergio', 'Busquets', 1, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Frenkie', 'de Jong', 1, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Pedri', '', 1, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Sergiño', 'Dest', 1, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Antoine', 'Griezmann', 1, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Ronald', 'Araújo', 1, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Sergi', 'Roberto', 1, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Karim', 'Benzema', 2, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Thibaut', 'Courtois', 2, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Raphael', 'Varane', 2, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Marcelo', '', 2, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Luka', 'Modric', 2, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Toni', 'Kroos', 2, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Eden', 'Hazard', 2, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Dani', 'Carvajal', 2, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Casemiro', '', 2, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Ferland', 'Mendy', 2, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Federico', 'Valverde', 2, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Cristiano', 'Ronaldo', 3, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Bruno', 'Fernandes', 3, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Paul', 'Pogba', 3, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Marcus', 'Rashford', 3, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Harry', 'Maguire', 3, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Luke', 'Shaw', 3, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Aaron', 'WanBissaka', 3, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Scott', 'McTominay', 3, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Fred', 'Rodrigues', 3, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Victor', 'Lindelof', 3, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Dean', 'Henderson', 3, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Robert', 'Lewndowski', 4, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Thomas', 'Mueller', 4, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Manuel', 'Neuer', 4, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('David', 'Alaba', 4, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Joshua', 'Kimmich', 4, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Leon', 'Goretzka', 4, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Niklas', 'Sule', 4, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Alphonso', 'Davies', 4, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Kingsley', 'Coman', 4, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Leroy', 'Sane', 4, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Corentin', 'Tolisso', 4, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Cristiano', 'Ronaldo', 5, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Giorgio', 'Chiellini', 5, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Leonardo', 'Bonucci', 5, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Federico', 'Chiesa', 5, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Arthur', 'Melocni', 5, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Juan', 'Cuadrado', 5, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Paulo', 'Dybala', 5, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Aaron', 'Ramsey', 5, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Weston', 'McKennie', 5, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Dejan', 'Kulusevski', 5, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Wojciech', 'Szczesny', 5, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Mohamed', 'Salah', 6, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Sadio', 'Mane', 6, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Virgil', 'van Dijk', 6, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Alexander', 'Arnold', 6, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Andrew', 'Robertson', 6, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Jordan', 'Henderson', 6, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Fabinho', 'Tavares', 6, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Diogo', 'Jota', 6, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Joel', 'Matip', 6, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Thiago', 'Alcantara', 6, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Alisson', 'Becker', 6, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Kylian', 'Mbappe', 7, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Neymar', 'Jr', 7, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Angel', 'Di Maria', 7, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Marco', 'Verratti', 7, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Presnel', 'Kimpembe', 7, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Marquinhos', '', 7, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Leandro', 'Paredes', 7, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Keylor', 'Navas', 7, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Achraf', 'Hakimi', 7, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Mauro', 'Icardi', 7, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Georginio', 'Wijnaldum', 7, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Golo', 'Kante', 8, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Mason', 'Mount', 8, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Timo', 'Werner', 8, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Cesar', 'Azplicueta', 8, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Kai', 'Havertz', 8, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Ben', 'Chilwell', 8, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Jorginho', '', 8, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Thiago', 'Silva', 8, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Reece', 'James', 8, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Edouard', 'Mendy', 8, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Hakim', 'Ziyech', 8, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Pierre', 'Aubameyang', 9, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Bukayo', 'Saka', 9, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Thomas', 'Partey', 9, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Gabriel', 'Magalhaes', 9, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Emile', 'Smith Rowe', 9, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Kieran', 'Tierney', 9, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Nicolas', 'Pepe', 9, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Bernd', 'Leno', 9, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Hector', 'Bellerin', 9, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Granit', 'Xhaka', 9, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Rob', 'Holding', 9, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Gianluigi', 'Donnarumma', 10, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Theo', 'Hernandez', 10, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Franck', 'Kessie', 10, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Simon', 'Kjaer', 10, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Ante', 'Rebic', 10, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Ismael', 'Bennacer', 10, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Rafael', 'Leao', 10, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Alessio', 'Romagnoli', 10, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Sandro', 'Tonali', 10, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Zlatan', 'Ibraimovic', 10, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Davide', 'Calabria', 10, 'Defender');

insert into Players (players_name, players_surname, team_id, position) values ('Luis', 'Garcia', 1, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Marc', 'Lopez', 2, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Ryan', 'Wilson', 3, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Julian', 'Muller', 4, 'Goalkeeper');
insert into Players (players_name, players_surname, team_id, position) values ('Matteo', 'Rossi', 5, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Adam', 'Johnson', 6, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Antoine', 'Dubois', 7, 'Forward');
insert into Players (players_name, players_surname, team_id, position) values ('Oliver', 'Baker', 8, 'Midfielder');
insert into Players (players_name, players_surname, team_id, position) values ('Samuel', 'Wright', 9, 'Defender');
insert into Players (players_name, players_surname, team_id, position) values ('Leonardo', 'Ricci', 10, 'Forward');

insert into Coaches (player_id, coaching_role) values (111, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (112, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (113, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (114, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (115, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (116, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (117, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (118, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (119, 'Head Coach');
insert into Coaches (player_id, coaching_role) values (120, 'Head Coach');

insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (1, 1, '2021-05-10', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (2, 2, '2021-06-15', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (3, 3, '2021-07-02', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (4, 4, '2021-05-18', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (5, 5, '2021-06-27', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (6, 6, '2021-07-12', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (7, 7, '2021-05-05', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (8, 8, '2021-06-20', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (9, 9, '2021-07-28', NULL);
insert into HasCoached (coach_id, team_id, in_transfer_date, out_transfer_date) values (10, 10, '2021-05-14', NULL);

insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (1, 1, '2020-05-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (2, 1, '2020-06-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (3, 1, '2020-07-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (4, 1, '2020-08-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (5, 1, '2020-05-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (6, 1, '2020-06-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (7, 1, '2020-07-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (8, 1, '2020-08-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (9, 1, '2020-05-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (10, 1, '2020-06-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (11, 1, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (12, 2, '2020-05-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (13, 2, '2020-06-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (14, 2, '2020-07-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (15, 2, '2020-08-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (16, 2, '2020-05-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (17, 2, '2020-06-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (18, 2, '2020-07-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (19, 2, '2020-08-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (20, 2, '2020-05-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (21, 2, '2020-06-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (22, 2, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (23, 3, '2020-05-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (24, 3, '2020-06-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (25, 3, '2020-07-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (26, 3, '2020-08-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (27, 3, '2020-05-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (28, 3, '2020-06-30', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (29, 3, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (30, 3, '2020-08-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (31, 3, '2020-05-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (32, 3, '2020-06-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (33, 3, '2020-07-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (34, 4, '2020-08-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (35, 4, '2020-05-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (36, 4, '2020-06-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (37, 4, '2020-07-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (38, 4, '2020-08-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (39, 4, '2020-05-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (40, 4, '2020-06-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (41, 4, '2020-07-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (42, 4, '2020-08-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (43, 4, '2020-05-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (44, 4, '2020-06-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (45, 5, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (46, 5, '2020-05-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (47, 5, '2020-06-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (48, 5, '2020-07-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (49, 5, '2020-08-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (50, 5, '2020-05-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (51, 5, '2020-06-30', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (52, 5, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (53, 5, '2020-08-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (54, 5, '2020-05-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (55, 5, '2020-06-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (56, 6, '2020-07-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (57, 6, '2020-08-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (58, 6, '2020-05-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (59, 6, '2020-06-30', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (60, 6, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (61, 6, '2020-08-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (62, 6, '2020-05-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (63, 6, '2020-06-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (64, 6, '2020-05-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (65, 6, '2020-06-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (66, 6, '2020-07-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (67, 7, '2020-08-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (68, 7, '2020-05-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (69, 7, '2020-06-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (70, 7, '2020-07-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (71, 7, '2020-08-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (72, 7, '2020-05-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (73, 7, '2020-06-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (74, 7, '2020-07-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (75, 7, '2020-08-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (76, 7, '2020-05-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (77, 7, '2020-06-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (78, 8, '2020-07-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (79, 8, '2020-08-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (80, 8, '2020-05-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (81, 8, '2020-06-30', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (82, 8, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (83, 8, '2020-08-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (84, 8, '2020-05-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (85, 8, '2020-06-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (86, 8, '2020-07-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (87, 8, '2020-08-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (88, 8, '2020-05-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (89, 9, '2020-06-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (90, 9, '2020-07-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (91, 9, '2020-08-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (92, 9, '2020-05-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (93, 9, '2020-06-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (94, 9, '2020-07-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (95, 9, '2020-08-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (96, 9, '2020-05-25', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (97, 9, '2020-06-30', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (98, 9, '2020-07-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (99, 9, '2020-08-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (100, 10, '2020-05-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (101, 10, '2020-06-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (102, 10, '2020-07-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (103, 10, '2020-08-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (104, 10, '2020-05-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (105, 10, '2020-06-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (106, 10, '2020-07-01', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (107, 10, '2020-08-10', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (108, 10, '2020-05-15', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (109, 10, '2020-06-20', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (110, 10, '2020-07-05', NULL);
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (111, 1, '1999-05-18', '2005-05-18');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (112, 2, '1994-08-10', '2001-08-10');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (113, 3, '2003-02-27', '2010-02-27');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (114, 4, '1997-11-21', '2004-11-21');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (115, 5, '1992-12-03', '1999-12-03');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (116, 6, '1998-07-06', '2005-07-06');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (117, 7, '1995-04-14', '2002-04-14');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (118, 8, '1996-09-29', '2003-09-29');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (119, 9, '1993-06-08', '2000-06-08');
insert into HasPlayed (player_id, team_id, in_transfer_date, out_transfer_date) values (120, 10, '1999-01-17', '2006-01-17');

insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (1, 2, 3, 1, '2022-09-01', '01:32:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (2, 3, 4, 0, '2022-09-13', '01:38:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (3, 4, 2, 5, '2022-09-25', '01:40:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (4, 5, 1, 2, '2022-10-07', '01:35:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (5, 6, 0, 4, '2022-10-19', '01:37:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (6, 7, 5, 2, '2022-10-31', '01:39:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (7, 8, 1, 3, '2022-11-12', '01:36:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (8, 9, 2, 0, '2022-11-24', '01:40:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (9, 10, 3, 2, '2022-12-06', '01:33:00');
insert into Games (home_team_id, away_team_id, home_teams_score, away_teams_score, games_date, duration) values (10, 1, 0, 1, '2022-12-18', '01:38:00');

insert into GameEvents (game_id, player_id, moment, event_type) values (1, 1, 12, 'ΓΚΟΛ');
insert into GameEvents (game_id, player_id, moment, event_type) values (1, 2, 23, 'ΓΚΟΛ');
insert into GameEvents (game_id, player_id, moment, event_type) values (1, 1, 42, 'ΠΕΝΑΛΤΙ');
insert into GameEvents (game_id, player_id, moment, event_type) values (1, 1, 45, 'ΓΚΟΛ');
insert into GameEvents (game_id, player_id, moment, event_type) values (1, 14, 18, 'ΓΚΟΛ');
insert into GameEvents (game_id, player_id, moment, event_type) values (2, 13, 33, 'ΓΚΟΛ');
insert into GameEvents (game_id, player_id, moment, event_type) values (2, 13, 59, 'ΓΚΟΛ');
insert into GameEvents (game_id, player_id, moment, event_type) values (2, 13, 10, 'ΓΚΟΛ');
insert into GameEvents (game_id, player_id, moment, event_type) values (2, 15, 36, 'ΓΚΟΛ');

insert into PlayerGameStatistics (player_id, team_id, game_id, red_cards, yellow_cards, goals, canceled_goals, active_time, penalties, corners) values (1, 1, 1, 0, 0, 2, 1, '01:32:00', 1, 5);
insert into PlayerGameStatistics (player_id, team_id, game_id, red_cards, yellow_cards, goals, canceled_goals, active_time, penalties, corners) values (2, 1, 1, 1, 0, 1, 2, '01:32:00', 0, 5);
insert into PlayerGameStatistics (player_id, team_id, game_id, red_cards, yellow_cards, goals, canceled_goals, active_time, penalties, corners) values (14, 2, 1, 0, 1, 2, 1, '01:32:00', 0, 5);
insert into PlayerGameStatistics (player_id, team_id, game_id, red_cards, yellow_cards, goals, canceled_goals, active_time, penalties, corners) values (13, 1, 2, 0, 1, 3, 0, '01:38:00', 0, 5);
insert into PlayerGameStatistics (player_id, team_id, game_id, red_cards, yellow_cards, goals, canceled_goals, active_time, penalties, corners) values (15, 1, 2, 0, 0, 1, 1, '01:38:00', 0, 5);
